[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[[services]]
name = "signal-moderation-bot"

[services.variables]
PORT = "5000"
SIGNAL_API_PORT = "8080"

[services.healthcheck]
path = "/health"
timeout = 30

